apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-service
  namespace: homevalue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-service
  template:
    metadata:
      labels:
        app: history-service
    spec:
      containers:
        - name: history-service
          image: 377002868387.dkr.ecr.us-east-1.amazonaws.com/homevalue-history:latest
          ports:
            - containerPort: 8001
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_NAME
              value: "homevalue_db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres123"
            - name: DB_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: history-service
  namespace: homevalue
spec:
  selector:
    app: history-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer